---
# tasks file for roles/sysadmin.nginx
# Ref: https://linuxize.com/post/how-to-install-nginx-on-ubuntu-16-04/
- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo='ppa:nginx/stable' update_cache=yes

- name: Install nginx
  apt:
    name: "{{ item }}"
  with_items:
    - nginx

- name: enable service nginx
  systemd:
    name: nginx
    enabled: yes
    masked: no

- name: Make nginx service is running
  systemd:
    state: started
    name: nginx

- name: Remove default nginx
  file:
    path: "/etc/nginx/sites-available/default"
    state: absent
  notify: restart nginx

- name: Remove default nginx
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: restart nginx